image: python:3.6-stretch

stages:
  - deploy

pages:
  stage: deploy
  when: on_success
  only:
    - master
  script:
    - mkdir public
    - cd docs
    - make html
    - mv _build/html/* ../public/
  artifacts:
    paths:
      - public
deploy-STAGING:  
   stage: deploy  
   before_script:
      - mkdir -p ~/.ssh     
      - echo -e "$STAGING_KEY" > ~/.ssh/id_rsa    
      - chmod 600 ~/.ssh/id_rsa     
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'  
   script:  
      - ssh e4esysadmin@104.225.217.155 "cd openhisa_sec8 && git pull && fuser -k 1987/tcp && sudo systemctl restart open_hisa "  
   environment:    
     name: production  
   only:   
     refs:      
       - STAGING  
   when: manual


