# Generated by Django 2.2.7 on 2020-03-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enrollment', '0002_planregistration_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='planregistration',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
