# Generated by Django 2.2.7 on 2020-03-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_enrollment', '0003_planregistration_is_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planregistration',
            old_name='reminder_sent',
            new_name='is_due_reminder_sent',
        ),
        migrations.AddField(
            model_name='planregistration',
            name='three_month_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
